### ISSUE TITLE
Segmentation faults encrypt() function.

### ISSUE THREAD

**Issue by nedark** [greensea/mptunnel#1]
I'm getting segmentations faults related to the encrypt() function.
Is the use of this function mandatory or can it be disabled easily?
Actually I dont need any encryption since I will use the tunnel for a OpenVPN connection, which is encrypted itself.

**Comment by greensea** [comment]
I have pushed a commit, you can disable encryption by setting environment variable MPTUNNEL_ENCRYPT to 0.

You can launch with the command:

```
MPTUNNEL_ENCRYPT=0 mpserver 1234 1.2.3.4 1234
```

Remember to do the same thing with mpclient, both server and client must be running in encryption mode or non-encryption mode.

And could you send me the dump file while segmentation faults? So I can locate and fix the bug.

**Comment by nedark** [comment]
Solved, thanks :)
