### ISSUE TITLE
README: compare mptunnel with mlvpn, or mention mlvpn

### ISSUE THREAD

**Issue by stapelberg** [greensea/mptunnel#9]
In the README, you write:

> MPTCP(MultiPath TCP) is a good idea to make network connection robust, but it only works on TCP. I was searching for MPUDP implementation but got nothing, so I write this tool.

I found https://github.com/zehome/MLVPN, which seems to fulfill the same goals (aggregate multiple links, transparently fail over between links) and seems like it would be a bit simpler to get going (instead of mptunnel + OpenVPN, you only need mlvpn).

I’m guessing you just did not happen to stumble upon mlvpn during your research, because mlvpn is actually older than mptunnel :).

Could you please update the README file to either:
1. Simply make people aware of alternative solutions so that they can decide which one they like best.
2. Compare the features of mptunnel vs. mlvpn, to make the decision easier for people.

Thank you!

**Comment by greensea** [comment]
Late for reply... I am in busy time these days.
No I never hear about mlvpn, I'll take some time to have a look at it.

**Comment by greensea** [comment]
Just metion mlvpn in README, no enough time to do a comparison. Anyway , thanks for you work.

**Comment by Bumpalert** [comment]
Hey,, I was checking OpenMPTCP router on multiple ways. I think MLTCP will be easier. My problems are listed here https://github.com/Ysurac/openmptcprouter/discussions/1758
